// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class StoredConversation {
  final String id;
  final String title;
  final String? providerAccount;
  final String createdAt;
  final String? currentLeafId;
  final PlatformInt64 updatedAt;
  final List<StoredMessage> messages;

  const StoredConversation({
    required this.id,
    required this.title,
    this.providerAccount,
    required this.createdAt,
    this.currentLeafId,
    required this.updatedAt,
    required this.messages,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      providerAccount.hashCode ^
      createdAt.hashCode ^
      currentLeafId.hashCode ^
      updatedAt.hashCode ^
      messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredConversation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          providerAccount == other.providerAccount &&
          createdAt == other.createdAt &&
          currentLeafId == other.currentLeafId &&
          updatedAt == other.updatedAt &&
          messages == other.messages;
}

class StoredMessage {
  final String id;
  final String conversationId;
  final String role;
  final String text;
  final String? parentId;
  final String childrenIds;
  final String? originalContent;
  final bool hasError;
  final String? activeChildId;
  final String? toolCallId;
  final String? toolCallsJson;
  final String createdAt;
  final bool cleared;
  final String? clearedSummary;
  final String? refetchArgs;
  final bool isCompactionSummary;
  final PlatformInt64? promptTokens;
  final PlatformInt64? completionTokens;
  final PlatformInt64? totalTokens;
  final String? reasoning;

  const StoredMessage({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.text,
    this.parentId,
    required this.childrenIds,
    this.originalContent,
    required this.hasError,
    this.activeChildId,
    this.toolCallId,
    this.toolCallsJson,
    required this.createdAt,
    required this.cleared,
    this.clearedSummary,
    this.refetchArgs,
    required this.isCompactionSummary,
    this.promptTokens,
    this.completionTokens,
    this.totalTokens,
    this.reasoning,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      role.hashCode ^
      text.hashCode ^
      parentId.hashCode ^
      childrenIds.hashCode ^
      originalContent.hashCode ^
      hasError.hashCode ^
      activeChildId.hashCode ^
      toolCallId.hashCode ^
      toolCallsJson.hashCode ^
      createdAt.hashCode ^
      cleared.hashCode ^
      clearedSummary.hashCode ^
      refetchArgs.hashCode ^
      isCompactionSummary.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode ^
      reasoning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          role == other.role &&
          text == other.text &&
          parentId == other.parentId &&
          childrenIds == other.childrenIds &&
          originalContent == other.originalContent &&
          hasError == other.hasError &&
          activeChildId == other.activeChildId &&
          toolCallId == other.toolCallId &&
          toolCallsJson == other.toolCallsJson &&
          createdAt == other.createdAt &&
          cleared == other.cleared &&
          clearedSummary == other.clearedSummary &&
          refetchArgs == other.refetchArgs &&
          isCompactionSummary == other.isCompactionSummary &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          reasoning == other.reasoning;
}
