// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A fetched page.
class FetchedPage {
  final String url;
  final String title;
  final String content;
  final String contentType;

  const FetchedPage({
    required this.url,
    required this.title,
    required this.content,
    required this.contentType,
  });

  @override
  int get hashCode =>
      url.hashCode ^ title.hashCode ^ content.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchedPage &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          content == other.content &&
          contentType == other.contentType;
}

/// A provider problem that did not necessarily fail the whole search.
class ProviderIssue {
  final String provider;
  final String kind;
  final String detail;
  final BigInt? retryAfterSecs;

  const ProviderIssue({
    required this.provider,
    required this.kind,
    required this.detail,
    this.retryAfterSecs,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      kind.hashCode ^
      detail.hashCode ^
      retryAfterSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderIssue &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          kind == other.kind &&
          detail == other.detail &&
          retryAfterSecs == other.retryAfterSecs;
}

/// Search results plus any provider issues encountered during fan-out.
class SearchBatch {
  final List<SearchResult> results;
  final List<ProviderIssue> issues;
  final List<String> successfulProviders;

  const SearchBatch({
    required this.results,
    required this.issues,
    required this.successfulProviders,
  });

  @override
  int get hashCode =>
      results.hashCode ^ issues.hashCode ^ successfulProviders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchBatch &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          issues == other.issues &&
          successfulProviders == other.successfulProviders;
}

/// A single search result.
class SearchResult {
  final String title;
  final String url;
  final String snippet;
  final PlatformInt64? publishedAt;

  /// Which provider produced this result.
  final String provider;

  const SearchResult({
    required this.title,
    required this.url,
    required this.snippet,
    this.publishedAt,
    required this.provider,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      url.hashCode ^
      snippet.hashCode ^
      publishedAt.hashCode ^
      provider.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url &&
          snippet == other.snippet &&
          publishedAt == other.publishedAt &&
          provider == other.provider;
}
