// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/conversations.dart';
import 'api/web_retrieval.dart';
import 'conversations/db.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'web_retrieval/provider.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  GenerationCheckpoint dco_decode_box_autoadd_generation_checkpoint(
    dynamic raw,
  );

  @protected
  GenerationClaim dco_decode_box_autoadd_generation_claim(dynamic raw);

  @protected
  GenerationFinish dco_decode_box_autoadd_generation_finish(dynamic raw);

  @protected
  GenerationTask dco_decode_box_autoadd_generation_task(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NewGenerationCommand dco_decode_box_autoadd_new_generation_command(
    dynamic raw,
  );

  @protected
  NewGenerationLifecycleEvent
  dco_decode_box_autoadd_new_generation_lifecycle_event(dynamic raw);

  @protected
  NewGenerationTask dco_decode_box_autoadd_new_generation_task(dynamic raw);

  @protected
  ProviderCall dco_decode_box_autoadd_provider_call(dynamic raw);

  @protected
  StoredConversation dco_decode_box_autoadd_stored_conversation(dynamic raw);

  @protected
  ToolExecution dco_decode_box_autoadd_tool_execution(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  FetchedPage dco_decode_fetched_page(dynamic raw);

  @protected
  GenerationCheckpoint dco_decode_generation_checkpoint(dynamic raw);

  @protected
  GenerationClaim dco_decode_generation_claim(dynamic raw);

  @protected
  GenerationCommand dco_decode_generation_command(dynamic raw);

  @protected
  GenerationFinish dco_decode_generation_finish(dynamic raw);

  @protected
  GenerationLifecycleEvent dco_decode_generation_lifecycle_event(dynamic raw);

  @protected
  GenerationRun dco_decode_generation_run(dynamic raw);

  @protected
  GenerationTask dco_decode_generation_task(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FetchedPage> dco_decode_list_fetched_page(dynamic raw);

  @protected
  List<GenerationCommand> dco_decode_list_generation_command(dynamic raw);

  @protected
  List<GenerationLifecycleEvent> dco_decode_list_generation_lifecycle_event(
    dynamic raw,
  );

  @protected
  List<GenerationRun> dco_decode_list_generation_run(dynamic raw);

  @protected
  List<GenerationTask> dco_decode_list_generation_task(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderCall> dco_decode_list_provider_call(dynamic raw);

  @protected
  List<ProviderConfig> dco_decode_list_provider_config(dynamic raw);

  @protected
  List<ProviderIssue> dco_decode_list_provider_issue(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<StoredConversation> dco_decode_list_stored_conversation(dynamic raw);

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw);

  @protected
  List<ToolExecution> dco_decode_list_tool_execution(dynamic raw);

  @protected
  NewGenerationCommand dco_decode_new_generation_command(dynamic raw);

  @protected
  NewGenerationLifecycleEvent dco_decode_new_generation_lifecycle_event(
    dynamic raw,
  );

  @protected
  NewGenerationTask dco_decode_new_generation_task(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GenerationClaim? dco_decode_opt_box_autoadd_generation_claim(dynamic raw);

  @protected
  GenerationTask? dco_decode_opt_box_autoadd_generation_task(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ProviderCall dco_decode_provider_call(dynamic raw);

  @protected
  ProviderConfig dco_decode_provider_config(dynamic raw);

  @protected
  ProviderIssue dco_decode_provider_issue(dynamic raw);

  @protected
  SearchBatch dco_decode_search_batch(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  StoredConversation dco_decode_stored_conversation(dynamic raw);

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw);

  @protected
  ToolExecution dco_decode_tool_execution(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  GenerationCheckpoint sse_decode_box_autoadd_generation_checkpoint(
    SseDeserializer deserializer,
  );

  @protected
  GenerationClaim sse_decode_box_autoadd_generation_claim(
    SseDeserializer deserializer,
  );

  @protected
  GenerationFinish sse_decode_box_autoadd_generation_finish(
    SseDeserializer deserializer,
  );

  @protected
  GenerationTask sse_decode_box_autoadd_generation_task(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NewGenerationCommand sse_decode_box_autoadd_new_generation_command(
    SseDeserializer deserializer,
  );

  @protected
  NewGenerationLifecycleEvent
  sse_decode_box_autoadd_new_generation_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  NewGenerationTask sse_decode_box_autoadd_new_generation_task(
    SseDeserializer deserializer,
  );

  @protected
  ProviderCall sse_decode_box_autoadd_provider_call(
    SseDeserializer deserializer,
  );

  @protected
  StoredConversation sse_decode_box_autoadd_stored_conversation(
    SseDeserializer deserializer,
  );

  @protected
  ToolExecution sse_decode_box_autoadd_tool_execution(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  FetchedPage sse_decode_fetched_page(SseDeserializer deserializer);

  @protected
  GenerationCheckpoint sse_decode_generation_checkpoint(
    SseDeserializer deserializer,
  );

  @protected
  GenerationClaim sse_decode_generation_claim(SseDeserializer deserializer);

  @protected
  GenerationCommand sse_decode_generation_command(SseDeserializer deserializer);

  @protected
  GenerationFinish sse_decode_generation_finish(SseDeserializer deserializer);

  @protected
  GenerationLifecycleEvent sse_decode_generation_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  GenerationRun sse_decode_generation_run(SseDeserializer deserializer);

  @protected
  GenerationTask sse_decode_generation_task(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FetchedPage> sse_decode_list_fetched_page(SseDeserializer deserializer);

  @protected
  List<GenerationCommand> sse_decode_list_generation_command(
    SseDeserializer deserializer,
  );

  @protected
  List<GenerationLifecycleEvent> sse_decode_list_generation_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  List<GenerationRun> sse_decode_list_generation_run(
    SseDeserializer deserializer,
  );

  @protected
  List<GenerationTask> sse_decode_list_generation_task(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderCall> sse_decode_list_provider_call(
    SseDeserializer deserializer,
  );

  @protected
  List<ProviderConfig> sse_decode_list_provider_config(
    SseDeserializer deserializer,
  );

  @protected
  List<ProviderIssue> sse_decode_list_provider_issue(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredConversation> sse_decode_list_stored_conversation(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  );

  @protected
  List<ToolExecution> sse_decode_list_tool_execution(
    SseDeserializer deserializer,
  );

  @protected
  NewGenerationCommand sse_decode_new_generation_command(
    SseDeserializer deserializer,
  );

  @protected
  NewGenerationLifecycleEvent sse_decode_new_generation_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  NewGenerationTask sse_decode_new_generation_task(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GenerationClaim? sse_decode_opt_box_autoadd_generation_claim(
    SseDeserializer deserializer,
  );

  @protected
  GenerationTask? sse_decode_opt_box_autoadd_generation_task(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ProviderCall sse_decode_provider_call(SseDeserializer deserializer);

  @protected
  ProviderConfig sse_decode_provider_config(SseDeserializer deserializer);

  @protected
  ProviderIssue sse_decode_provider_issue(SseDeserializer deserializer);

  @protected
  SearchBatch sse_decode_search_batch(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  StoredConversation sse_decode_stored_conversation(
    SseDeserializer deserializer,
  );

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer);

  @protected
  ToolExecution sse_decode_tool_execution(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_generation_checkpoint(
    GenerationCheckpoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generation_claim(
    GenerationClaim self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generation_finish(
    GenerationFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generation_task(
    GenerationTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_generation_command(
    NewGenerationCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_generation_lifecycle_event(
    NewGenerationLifecycleEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_generation_task(
    NewGenerationTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_provider_call(
    ProviderCall self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stored_conversation(
    StoredConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tool_execution(
    ToolExecution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_fetched_page(FetchedPage self, SseSerializer serializer);

  @protected
  void sse_encode_generation_checkpoint(
    GenerationCheckpoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generation_claim(
    GenerationClaim self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generation_command(
    GenerationCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generation_finish(
    GenerationFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generation_lifecycle_event(
    GenerationLifecycleEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generation_run(GenerationRun self, SseSerializer serializer);

  @protected
  void sse_encode_generation_task(
    GenerationTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fetched_page(
    List<FetchedPage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_generation_command(
    List<GenerationCommand> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_generation_lifecycle_event(
    List<GenerationLifecycleEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_generation_run(
    List<GenerationRun> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_generation_task(
    List<GenerationTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_call(
    List<ProviderCall> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_config(
    List<ProviderConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_issue(
    List<ProviderIssue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_conversation(
    List<StoredConversation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tool_execution(
    List<ToolExecution> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_generation_command(
    NewGenerationCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_generation_lifecycle_event(
    NewGenerationLifecycleEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_generation_task(
    NewGenerationTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_generation_claim(
    GenerationClaim? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_generation_task(
    GenerationTask? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_provider_call(ProviderCall self, SseSerializer serializer);

  @protected
  void sse_encode_provider_config(
    ProviderConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_issue(ProviderIssue self, SseSerializer serializer);

  @protected
  void sse_encode_search_batch(SearchBatch self, SseSerializer serializer);

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_stored_conversation(
    StoredConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer);

  @protected
  void sse_encode_tool_execution(ToolExecution self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;
}
