// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/conversations.dart';
import 'api/web_retrieval.dart';
import 'conversations/db.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'web_retrieval/provider.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.10.0';

  @override
  int get rustContentHash => -1493713572;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'app_rust',
        ioDirectory: '../rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiConversationsConfigureConversations({
    required String dbPath,
  });

  Future<void> crateApiWebRetrievalConfigureWebRetrieval({
    required String dbPath,
    required List<ProviderConfig> searchProviders,
    required List<ProviderConfig> fetchProviders,
  });

  Future<void> crateApiConversationsDeleteConversation({required String id});

  Future<void> crateApiSimpleInitApp();

  Future<List<StoredConversation>> crateApiConversationsLoadConversations();

  Future<void> crateApiConversationsUpsertConversation({
    required StoredConversation conv,
  });

  Future<FetchedPage> crateApiWebRetrievalUrlFetch({
    required String url,
    required String format,
  });

  Future<void> crateApiWebRetrievalWebCacheCleanup();

  Future<List<FetchedPage>> crateApiWebRetrievalWebCacheSearchPages({
    required String query,
    required int limit,
  });

  Future<List<SearchResult>> crateApiWebRetrievalWebSearch({
    required String query,
    required int numResults,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiConversationsConfigureConversations({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConversationsConfigureConversationsConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationsConfigureConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "configure_conversations",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiWebRetrievalConfigureWebRetrieval({
    required String dbPath,
    required List<ProviderConfig> searchProviders,
    required List<ProviderConfig> fetchProviders,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_list_provider_config(searchProviders, serializer);
          sse_encode_list_provider_config(fetchProviders, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWebRetrievalConfigureWebRetrievalConstMeta,
        argValues: [dbPath, searchProviders, fetchProviders],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebRetrievalConfigureWebRetrievalConstMeta =>
      const TaskConstMeta(
        debugName: "configure_web_retrieval",
        argNames: ["dbPath", "searchProviders", "fetchProviders"],
      );

  @override
  Future<void> crateApiConversationsDeleteConversation({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConversationsDeleteConversationConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationsDeleteConversationConstMeta =>
      const TaskConstMeta(debugName: "delete_conversation", argNames: ["id"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<StoredConversation>> crateApiConversationsLoadConversations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_stored_conversation,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConversationsLoadConversationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationsLoadConversationsConstMeta =>
      const TaskConstMeta(debugName: "load_conversations", argNames: []);

  @override
  Future<void> crateApiConversationsUpsertConversation({
    required StoredConversation conv,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_stored_conversation(conv, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConversationsUpsertConversationConstMeta,
        argValues: [conv],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationsUpsertConversationConstMeta =>
      const TaskConstMeta(debugName: "upsert_conversation", argNames: ["conv"]);

  @override
  Future<FetchedPage> crateApiWebRetrievalUrlFetch({
    required String url,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fetched_page,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWebRetrievalUrlFetchConstMeta,
        argValues: [url, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebRetrievalUrlFetchConstMeta =>
      const TaskConstMeta(debugName: "url_fetch", argNames: ["url", "format"]);

  @override
  Future<void> crateApiWebRetrievalWebCacheCleanup() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWebRetrievalWebCacheCleanupConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebRetrievalWebCacheCleanupConstMeta =>
      const TaskConstMeta(debugName: "web_cache_cleanup", argNames: []);

  @override
  Future<List<FetchedPage>> crateApiWebRetrievalWebCacheSearchPages({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_fetched_page,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWebRetrievalWebCacheSearchPagesConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebRetrievalWebCacheSearchPagesConstMeta =>
      const TaskConstMeta(
        debugName: "web_cache_search_pages",
        argNames: ["query", "limit"],
      );

  @override
  Future<List<SearchResult>> crateApiWebRetrievalWebSearch({
    required String query,
    required int numResults,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(numResults, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWebRetrievalWebSearchConstMeta,
        argValues: [query, numResults],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebRetrievalWebSearchConstMeta =>
      const TaskConstMeta(
        debugName: "web_search",
        argNames: ["query", "numResults"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  StoredConversation dco_decode_box_autoadd_stored_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_stored_conversation(raw);
  }

  @protected
  FetchedPage dco_decode_fetched_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FetchedPage(
      url: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<FetchedPage> dco_decode_list_fetched_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fetched_page).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProviderConfig> dco_decode_list_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_provider_config).toList();
  }

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_result).toList();
  }

  @protected
  List<StoredConversation> dco_decode_list_stored_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stored_conversation).toList();
  }

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stored_message).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ProviderConfig dco_decode_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProviderConfig(
      kind: dco_decode_String(arr[0]),
      secret: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  SearchResult dco_decode_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchResult(
      title: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      snippet: dco_decode_String(arr[2]),
      publishedAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
      provider: dco_decode_String(arr[4]),
    );
  }

  @protected
  StoredConversation dco_decode_stored_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return StoredConversation(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      providerAccount: dco_decode_opt_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
      currentLeafId: dco_decode_opt_String(arr[4]),
      updatedAt: dco_decode_i_64(arr[5]),
      messages: dco_decode_list_stored_message(arr[6]),
    );
  }

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return StoredMessage(
      id: dco_decode_String(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
      text: dco_decode_String(arr[3]),
      parentId: dco_decode_opt_String(arr[4]),
      childrenIds: dco_decode_String(arr[5]),
      originalContent: dco_decode_opt_String(arr[6]),
      hasError: dco_decode_bool(arr[7]),
      activeChildId: dco_decode_opt_String(arr[8]),
      toolCallId: dco_decode_opt_String(arr[9]),
      toolCallsJson: dco_decode_opt_String(arr[10]),
      createdAt: dco_decode_String(arr[11]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  StoredConversation sse_decode_box_autoadd_stored_conversation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_stored_conversation(deserializer));
  }

  @protected
  FetchedPage sse_decode_fetched_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    return FetchedPage(
      url: var_url,
      title: var_title,
      content: var_content,
      contentType: var_contentType,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<FetchedPage> sse_decode_list_fetched_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FetchedPage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fetched_page(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProviderConfig> sse_decode_list_provider_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_config(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<StoredConversation> sse_decode_list_stored_conversation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoredConversation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stored_conversation(deserializer));
    }
    return ans_;
  }

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoredMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stored_message(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProviderConfig sse_decode_provider_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_secret = sse_decode_opt_String(deserializer);
    return ProviderConfig(kind: var_kind, secret: var_secret);
  }

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    var var_publishedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_provider = sse_decode_String(deserializer);
    return SearchResult(
      title: var_title,
      url: var_url,
      snippet: var_snippet,
      publishedAt: var_publishedAt,
      provider: var_provider,
    );
  }

  @protected
  StoredConversation sse_decode_stored_conversation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_providerAccount = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_currentLeafId = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_messages = sse_decode_list_stored_message(deserializer);
    return StoredConversation(
      id: var_id,
      title: var_title,
      providerAccount: var_providerAccount,
      createdAt: var_createdAt,
      currentLeafId: var_currentLeafId,
      updatedAt: var_updatedAt,
      messages: var_messages,
    );
  }

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_parentId = sse_decode_opt_String(deserializer);
    var var_childrenIds = sse_decode_String(deserializer);
    var var_originalContent = sse_decode_opt_String(deserializer);
    var var_hasError = sse_decode_bool(deserializer);
    var var_activeChildId = sse_decode_opt_String(deserializer);
    var var_toolCallId = sse_decode_opt_String(deserializer);
    var var_toolCallsJson = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return StoredMessage(
      id: var_id,
      conversationId: var_conversationId,
      role: var_role,
      text: var_text,
      parentId: var_parentId,
      childrenIds: var_childrenIds,
      originalContent: var_originalContent,
      hasError: var_hasError,
      activeChildId: var_activeChildId,
      toolCallId: var_toolCallId,
      toolCallsJson: var_toolCallsJson,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_stored_conversation(
    StoredConversation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stored_conversation(self, serializer);
  }

  @protected
  void sse_encode_fetched_page(FetchedPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.contentType, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_fetched_page(
    List<FetchedPage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fetched_page(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_provider_config(
    List<ProviderConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_config(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stored_conversation(
    List<StoredConversation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stored_conversation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stored_message(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_provider_config(
    ProviderConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.secret, serializer);
  }

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.snippet, serializer);
    sse_encode_opt_box_autoadd_i_64(self.publishedAt, serializer);
    sse_encode_String(self.provider, serializer);
  }

  @protected
  void sse_encode_stored_conversation(
    StoredConversation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.providerAccount, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_opt_String(self.currentLeafId, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_list_stored_message(self.messages, serializer);
  }

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_opt_String(self.parentId, serializer);
    sse_encode_String(self.childrenIds, serializer);
    sse_encode_opt_String(self.originalContent, serializer);
    sse_encode_bool(self.hasError, serializer);
    sse_encode_opt_String(self.activeChildId, serializer);
    sse_encode_opt_String(self.toolCallId, serializer);
    sse_encode_opt_String(self.toolCallsJson, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
