// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../conversations/db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db`

/// Initialize the conversations database: open the DB at `db_path`, run
/// migrations. `db_path` of empty string opens an in-memory database.
Future<void> configureConversations({required String dbPath}) => RustLib
    .instance
    .api
    .crateApiConversationsConfigureConversations(dbPath: dbPath);

/// Load all conversations with their message trees, most recent first.
Future<List<StoredConversation>> loadConversations() =>
    RustLib.instance.api.crateApiConversationsLoadConversations();

/// Upsert (insert or replace) a conversation and all its messages.
Future<void> upsertConversation({required StoredConversation conv}) =>
    RustLib.instance.api.crateApiConversationsUpsertConversation(conv: conv);

/// Delete a conversation and all its messages.
Future<void> deleteConversation({required String id}) =>
    RustLib.instance.api.crateApiConversationsDeleteConversation(id: id);
