// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../web_retrieval/provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_fetch_slot`, `build_search_slot`, `db`, `fetch_slots`, `search_slots`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Initialize the web-retrieval subsystem: open the DB at `db_path`, run
/// migrations, and register the given search + fetch providers.
///
/// `db_path` of empty string opens an in-memory database.
Future<void> configureWebRetrieval({
  required String dbPath,
  required List<ProviderConfig> searchProviders,
  required List<ProviderConfig> fetchProviders,
}) => RustLib.instance.api.crateApiWebRetrievalConfigureWebRetrieval(
  dbPath: dbPath,
  searchProviders: searchProviders,
  fetchProviders: fetchProviders,
);

/// Run a web search across all configured providers. Returns merged, deduped
/// results. Checks the cache first; caches per-provider results on miss.
Future<List<SearchResult>> webSearch({
  required String query,
  required int numResults,
}) => RustLib.instance.api.crateApiWebRetrievalWebSearch(
  query: query,
  numResults: numResults,
);

/// Fetch a single URL across all configured fetch providers. Returns the
/// first successful result. Checks the cache first.
Future<FetchedPage> urlFetch({required String url, required String format}) =>
    RustLib.instance.api.crateApiWebRetrievalUrlFetch(url: url, format: format);

/// Full-text search across all cached pages (BM25 ranked).
Future<List<FetchedPage>> webCacheSearchPages({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiWebRetrievalWebCacheSearchPages(
  query: query,
  limit: limit,
);

/// Delete cache entries older than the TTL. Call periodically.
Future<void> webCacheCleanup() =>
    RustLib.instance.api.crateApiWebRetrievalWebCacheCleanup();

/// Provider kind for configuration from Dart.
class ProviderConfig {
  final String kind;
  final String? secret;

  const ProviderConfig({required this.kind, this.secret});

  @override
  int get hashCode => kind.hashCode ^ secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderConfig &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          secret == other.secret;
}
